BATCH_SIZE = 1
NUM_WORKERS = 12
EPOCHS = 1
LR = 0.00008  # Learning Rate
WD = 0  # Weight Decay
GAMMA = 0.9
SAVE_MODEL = True
IMAGE_SIZE = 228
TRAIN = True  # Change to False for analyse model(s) by some metrics
NUM_CLASSES = 5  # Amount of classes to classify in the model according to the dataset
